using Fluxnote.Backend.Services.AI;

namespace Fluxnote.Backend.Tests.Fakes;

/// <summary>
/// Fake do serviço de IA para testes de integração.
/// Permite configurar respostas e simular erros sem chamar a API real do Gemini.
/// </summary>
public class TestAIService : IAIService
{
    /// <summary>
    /// Resumo que será retornado pelo GenerateSummaryAsync.
    /// </summary>
    public string SummaryToReturn { get; set; } = "This is a test summary generated by the AI service.";

    /// <summary>
    /// Se definida, o GenerateSummaryAsync lança esta exceção.
    /// </summary>
    public Exception? ExceptionToThrow { get; set; }

    /// <summary>
    /// Último texto recebido pelo GenerateSummaryAsync (para assertions).
    /// </summary>
    public string? LastReceivedText { get; private set; }

    /// <summary>
    /// Número de vezes que o GenerateSummaryAsync foi chamado.
    /// </summary>
    public int CallCount { get; private set; }

    public Task<string> GenerateSummaryAsync(string text)
    {
        CallCount++;
        LastReceivedText = text;

        if (ExceptionToThrow != null)
            throw ExceptionToThrow;

        return Task.FromResult(SummaryToReturn);
    }

    /// <summary>
    /// Texto melhorado que será retornado pelo ImproveTextAsync.
    /// </summary>
    public string ImprovedTextToReturn { get; set; } = "This is improved text generated by the AI service.";

    /// <summary>
    /// Último texto selecionado recebido pelo ImproveTextAsync (para assertions).
    /// </summary>
    public string? LastReceivedSelectedText { get; private set; }

    public Task<string> ImproveTextAsync(string selectedText, string fullDocumentText, IEnumerable<string>? contextTexts = null)
    {
        CallCount++;
        LastReceivedSelectedText = selectedText;

        if (ExceptionToThrow != null)
            throw ExceptionToThrow;

        return Task.FromResult(ImprovedTextToReturn);
    }

    /// <summary>
    /// Conteúdo que será retornado pelo GenerateContentAsync.
    /// </summary>
    public string GeneratedContentToReturn { get; set; } = "This is generated content from the AI service.";

    /// <summary>
    /// Último prompt recebido pelo GenerateContentAsync (para assertions).
    /// </summary>
    public string? LastReceivedPrompt { get; private set; }

    public Task<string> GenerateContentAsync(string prompt, string fullDocumentText, IEnumerable<string>? contextTexts = null)
    {
        CallCount++;
        LastReceivedPrompt = prompt;

        if (ExceptionToThrow != null)
            throw ExceptionToThrow;

        return Task.FromResult(GeneratedContentToReturn);
    }

    /// <summary>
    /// Repõe o estado do fake para valores iniciais.
    /// </summary>
    public void Reset()
    {
        SummaryToReturn = "This is a test summary generated by the AI service.";
        ImprovedTextToReturn = "This is improved text generated by the AI service.";
        GeneratedContentToReturn = "This is generated content from the AI service.";
        ExceptionToThrow = null;
        LastReceivedText = null;
        LastReceivedSelectedText = null;
        LastReceivedPrompt = null;
        CallCount = 0;
    }
}
