using Fluxnote.Backend.Services.AI;

namespace Fluxnote.Backend.Tests.Fakes;

/// <summary>
/// Fake do serviço de IA para testes de integração.
/// Permite configurar respostas e simular erros sem chamar a API real do Gemini.
/// </summary>
public class TestAIService : IAIService
{
    /// <summary>
    /// Resumo que será retornado pelo GenerateSummaryAsync.
    /// </summary>
    public string SummaryToReturn { get; set; } = "This is a test summary generated by the AI service.";

    /// <summary>
    /// Se definida, o GenerateSummaryAsync lança esta exceção.
    /// </summary>
    public Exception? ExceptionToThrow { get; set; }

    /// <summary>
    /// Último texto recebido pelo GenerateSummaryAsync (para assertions).
    /// </summary>
    public string? LastReceivedText { get; private set; }

    /// <summary>
    /// Número de vezes que o GenerateSummaryAsync foi chamado.
    /// </summary>
    public int CallCount { get; private set; }

    public Task<string> GenerateSummaryAsync(string text)
    {
        CallCount++;
        LastReceivedText = text;

        if (ExceptionToThrow != null)
            throw ExceptionToThrow;

        return Task.FromResult(SummaryToReturn);
    }

    /// <summary>
    /// Repõe o estado do fake para valores iniciais.
    /// </summary>
    public void Reset()
    {
        SummaryToReturn = "This is a test summary generated by the AI service.";
        ExceptionToThrow = null;
        LastReceivedText = null;
        CallCount = 0;
    }
}
